SRC_FILE    = \
        ../COMMON_FILES/CommonParam.F90 \
        ../COMMON_FILES/LaserParam.F90 \
        ../COMMON_FILES/mfd_solutions.F90 \
        ../COMMON_FILES/set_environment.F90 \
        ../COMMON_FILES/refine_DPG.F90 \
        ../COMMON_FILES/commonRoutines.F90 \
        set_3Dint_fi.F90 \
        celem.F90 \
        dirichlet.F90 \
        elem_fi.F90 \
        elem_residual_fi.F90 \
        exact.F90 \
        fake.F90 \
        getf.F90 \
        finalize.F90 \
        initialize.F90 \
        main.F90 \
        set_initial_mesh.F90 \
        soldis.F90

