Import("*")

filenames = Split("""
activate.F90
break.F90
close_mesh.F90
display_ref_kind.F90
nodbreak.F90
nodgen.F
p_refine.F90
random_refine.F90
refine.F90
refresh.F90
""")
#nodmod.F

shared_objs = env.SharedObject(filenames)

shared_objs += SConscript("break/SConscript")
shared_objs += SConscript("util/SConscript")

Return("shared_objs")
