Import("*")

filenames = Split("""
add_layer2plane.F90
add_prism_layer.F
surf_cone.F90
connect.F90
curve.F90
surf_cylinder.F90
surf_ellipsoid.F90
GMP_kernels.F90
block_hexa.F90
input_geometry.F
input_DEFAULT.F90
mnewt.F
surf_plane.F90
block_prism.F90
block_pyram.F90
read_imprec.F
fig_recta.F90
saruss.F
surf_sphere1.F90
split_surface.F90
surf.F90
block_tetra.F
fig_trian.F90
upgrade2double.F90
""")
#read_geometry.F90
#input_RECONSTRUCT.F
#input_NETGEN.F
#input_GMPdata.F
#pointr.F

shared_objs = env.SharedObject(filenames)

shared_objs += SConscript("curves/SConscript")
shared_objs += SConscript("triangles/SConscript")
shared_objs += SConscript("rectangles/SConscript")
shared_objs += SConscript("reconstruct/SConscript")

Return("shared_objs")
