#
#  general utilities
#
utilities = $(SRC_DIR)/utilities/clfil.F \
	$(SRC_DIR)/utilities/cparray.F \
	$(SRC_DIR)/utilities/cpvec.F \
	$(SRC_DIR)/utilities/cpveci.F \
	$(SRC_DIR)/utilities/decod3.F \
	$(SRC_DIR)/utilities/decod.F \
	$(SRC_DIR)/utilities/decode.F \
	$(SRC_DIR)/utilities/decode2.F \
	$(SRC_DIR)/utilities/decode3.F \
	$(SRC_DIR)/utilities/decode100.F \
	$(SRC_DIR)/utilities/decode_order.F \
	$(SRC_DIR)/utilities/decodg.F \
	$(SRC_DIR)/utilities/domain_number.F90 \
	$(SRC_DIR)/utilities/encod.F \
	$(SRC_DIR)/utilities/encode_order.F \
	$(SRC_DIR)/utilities/encodg.F \
	$(SRC_DIR)/utilities/findmin.F \
	$(SRC_DIR)/utilities/isgn.F \
	$(SRC_DIR)/utilities/iwrap.F \
	$(SRC_DIR)/utilities/keep_time.F \
	$(SRC_DIR)/utilities/legendre_polynomial.F \
	$(SRC_DIR)/utilities/locate.F \
	$(SRC_DIR)/utilities/locate_char.F \
	$(SRC_DIR)/utilities/mixed_product.F \
	$(SRC_DIR)/utilities/norm.F90 \
	$(SRC_DIR)/utilities/normalize.F \
	$(SRC_DIR)/utilities/number_of_faces.F90 \
	$(SRC_DIR)/utilities/opfil.F \
	$(SRC_DIR)/utilities/pause.F \
	$(SRC_DIR)/utilities/printm.F \
	$(SRC_DIR)/utilities/proj_line.F \
	$(SRC_DIR)/utilities/scalar_product.F90 \
	$(SRC_DIR)/utilities/setz.F \
	$(SRC_DIR)/utilities/setzi.F \
	$(SRC_DIR)/utilities/sort.F \
	$(SRC_DIR)/utilities/sortm.F \
	$(SRC_DIR)/utilities/spherical_bessel.F \
	$(SRC_DIR)/utilities/time.F \
	$(SRC_DIR)/utilities/int2str.F
