Import("*")

filenames = Split("""
communicators.F
constrained_nodes.F
constraints.F
control.F90
element_data.F
environment.F90
error.F90
kinds.F90
math_constants.F90
parallelism.F
parameters.F90
physics.F90
refinements.F90
upscale.F90
""")
#assembly.F90
#data_structure3D.F

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
