Import("*")

filenames = Split("""
bckwrd.F
complt.F
dest.F
desvec.F
elmrhs.F
elmsol.F
frwcp.F
frwrs.F
frwsr.F
locls.F
loclu.F
locr.F
resol.F
semrhs.F
surfsp.F
surfss.F
symasm.F
symelm.F
unsasm.F
unselm.F
zdiriodum.F
zdirio.F
zecond.F
zeror.F
zeros.F
zerou.F
""")

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
