Import("*")

filenames = Split("""
big_neig_across_face.F90
neig_across_face.F90
dof_in.F90
dof_out.F90
domain_number.F90
elem_face.F90
find_bc.F90
find_center.F90
find_domain.F90
find_elem_nodes.F90
find_element_size.F90
find_neig.F90
find_nrdof.F90
find_orient.F90
find_order.F90
mesh_show.F90
neig_face.F90
neig_show.F90
result.F
set_nodal_dof.F
""")
#nelcon.F

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
