Import("*")

filenames = Split("""
bezier.F90
curve_1SurfrCur.F
curve_1SurfsCur.F90
curve_2SurfrCur.F
curve_2SurfsCur.F
curve_3HermCur.F
curve_3SurfsCur.F90
curve_CylGeod.F
curve_HermCur.F
curve_ImpCir.F
curve_QuaCir.F
curve_SegCir.F
""")

#curve_cBezier.F

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
