Import("*")

filenames = Split("""
set_break.F90
set_bric_break.F90
set_edge_break.F90
set_pris_break.F90
set_pyra_break.F90
set_quad_break.F90
set_tetr_break.F90
set_trig_break.F90
""")

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
