Import("*")

shared_objs = SConscript("base/SConscript")
shared_objs += SConscript("interf/SConscript")
shared_objs += SConscript("module/SConscript")
shared_objs += SConscript("util/SConscript")

Return("shared_objs")
