Import("*")

filenames = Split("""
celem_system.F90
flag_constr_parents.F
get_connect_info.F
logic.F
logic_nodes.F
solelm.F
""")
#nodcor.F

shared_objs = env.SharedObject(filenames)

shared_objs += SConscript("util/SConscript")

Return("shared_objs")
