Import("*")

filenames = Split("""
trian_G1RecTri.F90
trian_ImpliTri.F
trian_PaSphTri.F
trian_PTITri.F90
trian_QtCirTri.F
trian_SpherTri.F
trian_TransTri.F
""")

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
