#
#  hp3d graphics routines (old)
#
hp3d_graphics = $(SRC_DIR)/hp3d_graphics/graphb.F \
        $(SRC_DIR)/hp3d_graphics/display_face.F \
        $(SRC_DIR)/hp3d_graphics/fincut.F \
        $(SRC_DIR)/hp3d_graphics/finlimb.F \
        $(SRC_DIR)/hp3d_graphics/grbody.F \
        $(SRC_DIR)/hp3d_graphics/int_coord.F \
        $(SRC_DIR)/hp3d_graphics/lsvisidb.F \
        $(SRC_DIR)/hp3d_graphics/soleval.F

#        $(SRC_DIR)/hp3d_graphics/section.F \
#        $(SRC_DIR)/hp3d_graphics/compute_section.F 

