Import("*")

filenames = Split("""
compute_face.F90
display_face.F
elem_no.F
fincut.F
finlimb.F90
graphb.F
grbody.F
int_coord.F
lsvisidb.F
set_x11_workspace.F90
soleval.F90
""")

shared_objs = env.SharedObject(filenames)

Return("shared_objs")
