Import("*")

filenames = Split("""
solvermod.F90
""")

shared_objs = env.SharedObject(filenames)

shared_objs += SConscript("frontal/SConscript")
shared_objs += SConscript("mumps/SConscript")
shared_objs += SConscript("uhm2/SConscript")

Return("shared_objs")
