SRC_FILE    = \
            PROJ.F90 \
            celem.F90 \
            elem.F90 \
            elem_h1.F90 \
            elem_hcurl.F90 \
            elem_hdiv.F90 \
            elem_l2.F90 \
            exact.F90 \
            fake.F90 \
            finalize.F90 \
            initialize.F90 \
            main.F90 \
            test_1.F90 \
            test_2.F90 \
            test_3.F90 \
            test_4.F90 \
            set_initial_mesh.F90 \
	    set_mesh_refinement.F90 \
            soldis.F90
