#
#  GMP graphics routines (old)
#
GMP_graphics = $(SRC_DIR)/GMP_graphics/dpallcu.F \
        $(SRC_DIR)/GMP_graphics/dpblno.F \
        $(SRC_DIR)/GMP_graphics/dptrno.F \
        $(SRC_DIR)/GMP_graphics/dpvistr.F \
        $(SRC_DIR)/GMP_graphics/findcoord.F \
        $(SRC_DIR)/GMP_graphics/findno.F \
        $(SRC_DIR)/GMP_graphics/GMPwireframe.F \
        $(SRC_DIR)/GMP_graphics/graphg.F \
        $(SRC_DIR)/GMP_graphics/lsvistr.F \
        $(SRC_DIR)/GMP_graphics/object2.F \
        $(SRC_DIR)/GMP_graphics/object3.F 

