Import("*")

import SCoptions

if SCoptions.complex:
    build_tutorials = SCoptions.complex_build_tutorials
else:
    build_tutorials = SCoptions.real_build_tutorials

for tutorial in build_tutorials:
    SConscript(tutorial+"/SConscript",
               variant_dir=tutorial+"_"+SCoptions.tutorial_build_dir_suffix)
