name: Linux Builds and Tests
run-name: linux-builds-and-tests

on:
  push:
    branches:
      - master
      - release
      - next
  workflow_dispatch:

jobs:
  linux-builds-and-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        mode: [real, complex]
        target: [dbg, opt]

    name: ${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}
    
    steps:
      # Print runner info to console
      - name: Print runner info
        run: |
          echo "This job was triggered by a ${{ github.event_name }} event."
          echo "This job is running on a ${{ runner.os }} server hosted by GitHub."
          echo "The repository name is ${{ github.repository }}."
          echo "The branch name is ${{ github.ref }}."

      # Interrupt workflow already running on the same branch
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Check out hp3d repository
      - name: Check out hp3d repository
        uses: actions/checkout@v4

      - run: echo "${{ github.repository }} repository has been cloned to the runner."

      # List files in the repository
      - name: List files in the repository
        run: ls ${{ github.workspace }}

      # Get MPI
      - name: Get MPI
        run: |
          sudo apt-get install mpich libmpich-dev

      # Check MPI
      - name: Check MPI
        run: |
          mpicc --version
          mpicxx --version
          mpif90 --version
          mpirun --version

      # Build PETSc
      - name: Build PETSc
        run: |
          echo "Getting latest PETSc release version"
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          
          echo "Configuring PETSc"
          cd petsc
          ./configure \
          --with-cc=mpicc --COPTFLAGS="-g -O" \
          --with-cxx=mpicxx --CXXOPTFLAGS="-g -O" \
          --with-fc=mpif90 --FOPTFLAGS="-g -O" \
          --with-mpiexec=mpirun \
          --download-fblaslapack=yes \
          --download-scalapack=yes \
          --download-mumps=yes \
          --download-metis=yes \
          --download-parmetis=yes \
          --download-ptscotch=yes \
          --download-zoltan=yes \
          --download-hdf5=yes \
          --with-hdf5-fortran-bindings=1 \
          --with-shared-libraries=0 \
          --with-debugging=0 \
          --with-scalar-type=${{ matrix.mode }} \
          --PETSC_ARCH=arch-${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.target }}

          echo "Building PETSc"
          make -j

          echo "Checking PETSc build"
          make check

      # Build hp3D
      - name: Build hp3D
        run: |
          echo "Configuring hp3D"
          cd trunk
          cp m_options_files/workflows/m_options_${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.target }} ./m_options

          echo "Building hp3D"
          make -j

          echo "Checking hp3D build"
          make check

      # Run hp3D tests
      - name: Run hp3D tests
        run: |
          echo "Running hp3D tests"
          cd trunk
          make test

      - run: echo "This job's status is ${{ job.status }}."

